language: php
dist: focal

matrix:
  fast_finish: true
  include:
    - php: '8.0'
    - php: '8.1'
    - php: '8.2'
      env: SNIFF=1
    - php: '8.3'
    - php: '8.4'
    - php: '8.5'

before_script:
  - composer install --no-interaction --prefer-dist || true
  - |
    if [[ "$SNIFF" == "1" ]]; then
      composer require --dev wp-coding-standards/wpcs:"^3.0" dealerdirect/phpcodesniffer-composer-installer:"^1.0" phpcompatibility/phpcompatibility-wp:"^2.1" --no-interaction
    fi
  - if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi

script:
  - find . -name '*.php' -not -path './vendor/*' -not -path './node_modules/*' | xargs -n 1 php -l
  - if [[ "$SNIFF" == "1" ]]; then jshint ./assets/js/clc-customizer.js ./assets/js/clc-preview.js; fi
  - if [[ "$SNIFF" == "1" ]]; then ./vendor/bin/phpcs; fi

notifications:
  email: false

cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.composer/cache
